---
controller_credentials:
  - name: PostgreSQL User Password - fastapi_tutorial
    description: Credential for fastapi_tutorial
    organization: Default
    credential_type: PostgreSQL User Password
    update_secrets: true
    inputs:
      postgres_password: "{{ vault_postgres_password }}"
  - name: FastAPI Application Secrets - fastapi_tutorial
    description: Credential for fastapi_tutorial
    organization: Default
    credential_type: FastAPI Application Secrets
    update_secrets: true
    inputs:
      database_url: "{{ vault_database_url }}"
      secret_key: "{{ vault_secret_key }}"
