---
argument_specs:
  main:
    short_description: Migrated to modern Ansible
    description:
      - This role installs and configures Nginx with multiple HTTPS sites, sets up security packages, firewall, SSH hardening, and generates self-signed 
        certificates.
    options:
      nginx_multisite_sites:
        type: dict
        required: false
        default:
          test.cluster.local:
            document_root: /opt/server/test
            ssl_enabled: true
          ci.cluster.local:
            document_root: /opt/server/ci
            ssl_enabled: true
          status.cluster.local:
            document_root: /opt/server/status
            ssl_enabled: true
        description: Mapping of site names to their configuration.
      nginx_multisite_ssl_certificate_path:
        type: str
        required: false
        default: /etc/ssl/certs
        description: Directory where SSL certificates are stored.
      nginx_multisite_ssl_private_key_path:
        type: str
        required: false
        default: /etc/ssl/private
        description: Directory where SSL private keys are stored.
      nginx_multisite_fail2ban_enabled:
        type: bool
        required: false
        default: true
        description: Enable Fail2Ban configuration.
      nginx_multisite_ufw_enabled:
        type: bool
        required: false
        default: true
        description: Enable UFW firewall configuration.
      nginx_multisite_ssh_disable_root:
        type: bool
        required: false
        default: true
        description: Disable SSH root login.
      nginx_multisite_ssh_password_auth:
        type: bool
        required: false
        default: false
        description: Disable SSH password authentication.
      nginx_multisite_secure_logging:
        type: bool
        required: false
        default: true
        description: Toggle secure logging for tasks handling secrets.
