- name: Deploy Nginx with Multiple Sites
  hosts: webservers
  become: true
  vars:
    ssl_certificate_path: /etc/ssl/certs
    ssl_private_key_path: /etc/ssl/private
    nginx_sites:
      example.com:
        document_root: /var/www/example.com
        ssl_enabled: true
      test.example.com:
        document_root: /var/www/test.example.com
        ssl_enabled: false
    security:
      fail2ban:
        enabled: true
        bantime: 3600
        findtime: 600
        maxretry: 3
        maxretry_limit_req: 10
        maxretry_botsearch: 2
  roles:
  - nginx_multisite
