---
- name: Install SSL packages
  ansible.builtin.package:
    name:
      - openssl
      - ca-certificates
    state: present
- name: Create ssl-cert group
  ansible.builtin.group:
    name: ssl-cert
    state: present
- name: Create SSL certificate directory
  ansible.builtin.file:
    path: "{{ ssl_certificate_path }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
- name: Create SSL private key directory
  ansible.builtin.file:
    path: "{{ ssl_private_key_path }}"
    owner: root
    group: ssl-cert
    mode: "0710"
    state: directory
- name: Generate self-signed SSL certificates for sites
  ansible.builtin.shell: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 \ -keyout {{ ssl_private_key_path }}/{{ item.key }}.key \ -out {{ ssl_certificate_path
    }}/{{ item.key }}.crt \ -subj "/C=US/ST=Example/L=Example/O=Example Org/OU=IT/CN={{ item.key }}/emailAddress=admin@example.com" chmod 640 {{ ssl_private_key_path
    }}/{{ item.key }}.key chown root:ssl-cert {{ ssl_private_key_path }}/{{ item.key }}.key '
  args:
    creates: "{{ ssl_certificate_path }}/{{ item.key }}.crt"
  loop: "{{ nginx_sites | dict2items }}"
  when: item.value.ssl_enabled | bool
  notify: Reload nginx
