---
- name: Include security tasks
  ansible.builtin.include_tasks: security.yml

- name: Include Nginx tasks
  ansible.builtin.include_tasks: nginx.yml

- name: Include TLS tasks
  ansible.builtin.include_tasks: ssl.yml

- name: Include site tasks
  ansible.builtin.include_tasks: sites.yml
