---
shared_state: false
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
    role-file: molecule/requirements.yml
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
      - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml
scenario:
  test_sequence:
  - dependency
  - destroy
  - create
  - prepare
  - converge
  - idempotence
  - verify
  - destroy
