- name: Configure Nginx with multiple sites
  hosts: webservers
  become: true
  vars:
    nginx_sites:
    - name: test.cluster.local
      document_root: /opt/server/test
      ssl_enabled: true
    - name: ci.cluster.local
      document_root: /opt/server/ci
      ssl_enabled: true
    - name: status.cluster.local
      document_root: /opt/server/status
      ssl_enabled: true
    ssl_enabled: true
    ssl_provider: self-signed
    fail2ban_enabled: true
    ssh_disable_root: true
    ssh_password_auth: false
  roles:
  - nginx_multisite
