---
fastapi_app_dir: /opt/fastapi-tutorial
fastapi_repo_url: https://github.com/dibanez/fastapi_tutorial.git
fastapi_repo_branch: main
fastapi_venv_dir: /opt/fastapi-tutorial/venv
fastapi_service_user: root
fastapi_host: 0.0.0.0
fastapi_port: 8000
fastapi_app_module: app.main:app
api_version: 1.0.0
fastapi_packages_debian:
  - python3
  - python3-pip
  - python3-venv
  - git
  - postgresql
  - postgresql-contrib
  - libpq-dev
fastapi_packages_redhat:
  - python3
  - python3-pip
  - git
  - postgresql-server
  - postgresql-contrib
  - postgresql-devel
