---
controller_credentials:
  - name: PostgreSQL FastAPI User - fastapi_tutorial
    description: Credential for fastapi_tutorial
    organization: Default
    credential_type: PostgreSQL FastAPI User
    update_secrets: true
    inputs:
      db_username: "{{ db_username }}"
      db_password: "{{ vault_db_password }}"
