---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
- name: Include security tasks
  ansible.builtin.include_tasks: security.yml
- name: Include SSL tasks
  ansible.builtin.include_tasks: ssl.yml
  when: ssl_enabled | bool
- name: Include sites tasks
  ansible.builtin.include_tasks: sites.yml
