---
controller_credentials:
  - name: PostgreSQL Database User - fastapi_tutorial
    description: PostgreSQL database user credentials for FastAPI application database connection
    organization: Default
    credential_type: PostgreSQL Database User
    update_secrets: true
    inputs:
      database_username: "{{ database_username }}"
      database_password: "{{ vault_database_password }}"
      database_name: "{{ database_name }}"
      database_host: "{{ database_host }}"
      database_port: "{{ database_port }}"
