---
controller_credentials:
- name: Redis Authentication - nginx_multisite
  description: Credential for nginx_multisite
  organization: Default
  credential_type: Redis Authentication
  update_secrets: true
  inputs:
    redis_password: '{{ vault_redis_password }}'
- name: PostgreSQL Database - nginx_multisite
  description: Credential for nginx_multisite
  organization: Default
  credential_type: PostgreSQL Database
  update_secrets: true
  inputs:
    db_username: '{{ db_username }}'
    db_password: '{{ vault_db_password }}'
    db_connection_string: '{{ vault_db_connection_string }}'
