---
controller_credentials:
  - name: PostgreSQL FastAPI Database - fastapi_tutorial
    description: Credentials for the local PostgreSQL database user used by the FastAPI tutorial application.
    organization: Default
    credential_type: PostgreSQL FastAPI Database
    update_secrets: true
    inputs:
      db_username: "{{ db_username }}"
      db_password: "{{ vault_db_password }}"
