---
controller_credentials:
- name: Redis Authentication - nginx_multisite
  description: Credential for nginx_multisite
  organization: Default
  credential_type: Redis Authentication
  update_secrets: true
  inputs:
    redis_password: '{{ vault_redis_password }}'
- name: PostgreSQL Database - nginx_multisite
  description: Credential for nginx_multisite
  organization: Default
  credential_type: PostgreSQL Database
  update_secrets: true
  inputs:
    database_password: '{{ vault_database_password }}'
    database_user: '{{ database_user }}'
