---
controller_credentials:
  - name: PostgreSQL Database - fastapi_tutorial
    description: Credentials for the FastAPI application to authenticate to its PostgreSQL database; the password should be migrated to Ansible Vault.
    organization: Default
    credential_type: PostgreSQL Database
    update_secrets: true
    inputs:
      database_username: "{{ database_username }}"
      database_password: "{{ vault_database_password }}"
