---
controller_credentials:
  - name: PostgreSQL FastAPI Database - fastapi_tutorial
    description: Credentials and connection settings for the FastAPI application's PostgreSQL database.
    organization: Default
    credential_type: PostgreSQL FastAPI Database
    update_secrets: true
    inputs:
      database_username: "{{ database_username }}"
      database_password: "{{ vault_database_password }}"
      database_name: "{{ database_name }}"
      database_host: "{{ database_host }}"
      database_port: "{{ database_port }}"
