---
- name: Ensure required variables are defined
  ansible.builtin.assert:
    that:
      - nginx_sites is defined
    fail_msg: Required variable 'nginx_sites' is not defined
    success_msg: All required variables are defined
  tags:
    - always
