---
- name: Apply security configuration
  ansible.builtin.import_tasks: security.yml

- name: Install and configure Nginx
  ansible.builtin.import_tasks: nginx.yml

- name: Install and configure TLS
  ansible.builtin.import_tasks: ssl.yml

- name: Configure Nginx sites
  ansible.builtin.import_tasks: sites.yml
