---
- name: Render Nginx virtual host configurations
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ item_nginx_vhost['key'] }} # noqa: R114 - filename from role-defined sites dictionary
    mode: "0644"
    backup: true
  loop: "{{ nginx_multisite_sites | dict2items }}"
  loop_control:
    loop_var: item_nginx_vhost
  notify: Validate and reload nginx
  vars:
    server_name: "{{ item_nginx_vhost['key'] }}"
    document_root: "{{ item_nginx_vhost['value']['document_root'] }}"
    ssl_enabled: "{{ item_nginx_vhost['value']['ssl_enabled'] }}"
    cert_file: "{{ nginx_multisite_certificate_path }}/{{ item_nginx_vhost['key'] }}.crt"
    key_file: "{{ nginx_multisite_private_key_path }}/{{ item_nginx_vhost['key'] }}.key"

- name: Enable Nginx virtual hosts
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item_nginx_enabled['key'] }} # noqa: R114 - filename from role-defined sites dictionary
    dest: /etc/nginx/sites-enabled/{{ item_nginx_enabled['key'] }} # noqa: R114 - filename from role-defined sites dictionary
    mode: "0644"
    state: link
    force: true
  loop: "{{ nginx_multisite_sites | dict2items }}"
  loop_control:
    loop_var: item_nginx_enabled
  notify: Validate and reload nginx

- name: Remove the default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    mode: "0644"
    state: absent
  notify: Validate and reload nginx
