---
fastapi_app_dir: /opt/fastapi-tutorial
fastapi_app_repo: https://github.com/dibanez/fastapi_tutorial.git
fastapi_app_branch: main
fastapi_app_port: 8000
fastapi_system_packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - postgresql
  - postgresql-contrib
  - libpq-dev
fastapi_db_user: "{{ db_username | default('fastapi') }}"
fastapi_db_name: "{{ db_name | default('fastapi_db') }}"
fastapi_db_host: "{{ db_host | default('localhost') }}"
fastapi_db_password: "{{ db_password | default('') }}"
fastapi_env_file: "{{ fastapi_app_dir }}/.env"
fastapi_env_file_mode: "0640"
fastapi_service_name: fastapi-tutorial
