---
- name: Include security configuration
  ansible.builtin.include_tasks: security.yml

- name: Include Nginx installation and configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Include TLS certificate configuration
  ansible.builtin.include_tasks: ssl.yml

- name: Include site configuration
  ansible.builtin.include_tasks: sites.yml
