---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload security sysctl
  ansible.builtin.shell:
    cmd: sysctl -p /etc/sysctl.d/99-security.conf
  changed_when: true
  args:
    executable: /bin/bash

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"
    state: restarted
