---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload security sysctl
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    sysctl_file: /etc/sysctl.d/99-security.conf
    state: present
    reload: true

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
