---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
- name: Deploy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx
- name: Deploy nginx security configuration
  ansible.builtin.template:
    src: security.conf.j2
    dest: /etc/nginx/conf.d/security.conf
    mode: "0644"
  notify: Reload nginx
- name: Create site document root directories
  ansible.builtin.file:
    path: "{{ item.value.document_root }}"
    owner: www-data
    group: www-data
    mode: "0755"
    state: directory
  loop: "{{ nginx_sites | dict2items }}"
- name: Deploy site index.html files
  ansible.builtin.copy:
    src: "{{ item.key.split('.') | first }}/index.html"
    dest: "{{ item.value.document_root }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
  loop: "{{ nginx_sites | dict2items }}"
- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
