---
- name: Validate required nginx role variables are defined
  ansible.builtin.assert:
    that:
      - nginx_sites is defined
      - nginx_sites | length > 0
      - nginx_ssl_certificate_path is defined
      - nginx_ssl_private_key_path is defined
    fail_msg: "One or more required nginx_multisite variables are not defined. Ensure nginx_sites, nginx_ssl_certificate_path, and nginx_ssl_private_key_path are
      set in defaults or extra vars.\n"
    quiet: true
