---
controller_credential_types:
- name: Redis Authentication
  description: Credential type for Redis Authentication
  kind: cloud
  inputs:
    fields:
    - id: redis_password
      type: string
      label: Redis Password
      secret: true
      help_text: Password for Redis authentication
    required:
    - redis_password
  injectors:
    extra_vars:
      redis_password: !unsafe '{{ redis_password }}'
- name: PostgreSQL Database
  description: Credential type for PostgreSQL Database
  kind: cloud
  inputs:
    fields:
    - id: database_password
      type: string
      label: Database Password
      secret: true
      help_text: Password for PostgreSQL database authentication
    - id: database_user
      type: string
      label: Database User
      help_text: Username for PostgreSQL database authentication
    required:
    - database_password
    - database_user
  injectors:
    extra_vars:
      database_password: !unsafe '{{ database_password }}'
      database_user: !unsafe '{{ database_user }}'
