---
controller_credential_types:
  - name: TLS Private Key Test
    description: Credential type for TLS Private Key Test
    kind: cloud
    inputs:
      fields:
        - id: private_key
          type: string
          label: Private Key
          secret: true
          help_text: TLS private key for test.cluster.local
      required:
        - private_key
    injectors:
      extra_vars:
        private_key: !unsafe "{{ private_key }}"
  - name: TLS Private Key CI
    description: Credential type for TLS Private Key CI
    kind: cloud
    inputs:
      fields:
        - id: private_key
          type: string
          label: Private Key
          secret: true
          help_text: TLS private key for ci.cluster.local
      required:
        - private_key
    injectors:
      extra_vars:
        private_key: !unsafe "{{ private_key }}"
  - name: TLS Private Key Status
    description: Credential type for TLS Private Key Status
    kind: cloud
    inputs:
      fields:
        - id: private_key
          type: string
          label: Private Key
          secret: true
          help_text: TLS private key for status.cluster.local
      required:
        - private_key
    injectors:
      extra_vars:
        private_key: !unsafe "{{ private_key }}"
