---
controller_credentials:
  - name: TLS Private Key Test - nginx_multisite
    description: Credential for nginx_multisite
    organization: Default
    credential_type: TLS Private Key Test
    update_secrets: true
    inputs:
      private_key: "{{ vault_private_key }}"
  - name: TLS Private Key CI - nginx_multisite
    description: Credential for nginx_multisite
    organization: Default
    credential_type: TLS Private Key CI
    update_secrets: true
    inputs:
      private_key: "{{ vault_private_key }}"
  - name: TLS Private Key Status - nginx_multisite
    description: Credential for nginx_multisite
    organization: Default
    credential_type: TLS Private Key Status
    update_secrets: true
    inputs:
      private_key: "{{ vault_private_key }}"
